services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root123
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
